global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_interval: 1m
  repeat_interval: 24h
  receiver: 'default'
  routes:
    - match:
        sistema: 'telegram'
      receiver: 'telegram'

receivers:
  - name: 'default'
    webhook_configs: []

  - name: 'telegram'
    telegram_configs:
      - bot_token: '8088506023:AAGRfgVI0LdJLrFfO6MinT_NUHNxV5EE7LY'
        api_url: 'https://api.telegram.org'
        chat_id: -1002335059207
        parse_mode: 'HTML'
        send_resolved: true
        message: "{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}{{ end }}"
